## Create a New Dataset with per Capita Values.

Defined as per-person, so we will take values and divide them by the population at the time for each country. This does not need to be performed on Life Ladder, Temperature, Clean Water, PM2.5, or Population. Also drop the changed columns to make a new dataset.

In [1]:
# Dependencies.
import pandas as pd

In [2]:
# Data.
df = pd.read_csv('ds19_happ_temp_cw_gg_pop_pm_co2.csv', index_col=['Country', 'Year'])
df.head()

                  Life Ladder  Temperature  Clean Water  \
Country     Year
Afghanistan 2010        4.758       14.629     48.28708
            2011        3.832       16.487     50.82785
            2012        3.783       14.373     53.40352
            2013        3.572       16.156     56.01404
            2014        3.131       15.647     58.65937

                  Greenhouse Gas Emissions  Population     PM2.5  \
Country     Year
Afghanistan 2010                   44910.0  29185511.0  52.49585
            2011                   58650.0  30117411.0  57.09972
            2012                   66750.0  31161378.0  55.46611
            2013                   74800.0  32269592.0  59.62277
            2014                   84620.0  33370804.0  62.72192

                  CO2 Emissions
Country     Year
Afghanistan 2010      8397779.0
            2011     12105788.0
            2012     10218514.0
            2013      8440766.0
            2014      7774340.0

In [3]:
# Make new columns, drop old ones.
df['pc Greenhouse Gas Emissions'] = df['Greenhouse Gas Emissions'] / df['Population']
df['pc CO2 Emissions'] = df['CO2 Emissions'] / df['Population']
df = df.drop(columns=['CO2 Emissions', 'Greenhouse Gas Emissions', 'Population'])
df.head()

                  Life Ladder  Temperature  Clean Water     PM2.5  \
Country     Year
Afghanistan 2010        4.758       14.629     48.28708  52.49585
            2011        3.832       16.487     50.82785  57.09972
            2012        3.783       14.373     53.40352  55.46611
            2013        3.572       16.156     56.01404  59.62277
            2014        3.131       15.647     58.65937  62.72192

                  pc Greenhouse Gas Emissions  pc CO2 Emissions
Country     Year
Afghanistan 2010                     0.001539          0.287738
            2011                     0.001947          0.401953
            2012                     0.002142          0.327922
            2013                     0.002318          0.261570
            2014                     0.002536          0.232968

In [4]:
# Save the dataset.
df.to_csv('ds31_all_per_capita_emissions.csv')