Using the Berkley Earth website, we gather data to get the average temperature in each of our countries in the month of June.

In [1]:
# Dependencies.
import pandas as pd
import requests
# For downloading files.
import urllib.request

In [2]:
# Get country dataset.
df = pd.read_csv('countries_happiness_2010_2019_2021.csv')
df.head()

,Country name,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021
0,Afghanistan,4.758,3.832,3.783,3.572,3.131,3.983,4.220,2.662,2.694,2.375,2.523
1,Albania,5.269,5.867,5.510,4.551,4.814,4.607,4.511,4.640,5.004,4.995,5.117
2,Argentina,6.441,6.776,6.468,6.582,6.671,6.697,6.427,6.039,5.793,6.086,5.929
3,Armenia,4.368,4.260,4.320,4.277,4.453,4.348,4.325,4.288,5.062,5.488,5.283
4,Australia,7.450,7.406,7.196,7.364,7.289,7.309,7.250,7.257,7.177,7.234,7.183

In [3]:
# Get the list of countries.
countries = df['Country name'].tolist()
countries[:5]

['Afghanistan', 'Albania', 'Argentina', 'Armenia', 'Australia']

In [4]:
# Get the textual data from Berkeley Earth, and save it for each country.
for country in countries:
    try:
        country_url = country
        if ' ' in country:
            country_url = country.replace(' ', '-')
        urllib.request.urlretrieve(f'http://berkeleyearth.lbl.gov/auto/Regional/TAVG/Text/{country_url.lower()}-TAVG-Trend.txt', f'be_text/{country}_temp.txt')
        print(f'{country} completed.')
    except:
        print(f'COUNTRY FAILED - {country}')

Afghanistan completed.
Albania completed.
Argentina completed.
Armenia completed.
Australia completed.
Austria completed.
Azerbaijan completed.
Bangladesh completed.
Belarus completed.
Belgium completed.
Bolivia completed.
Bosnia and Herzegovina completed.
Botswana completed.
Brazil completed.
Bulgaria completed.
Burkina Faso completed.
Cambodia completed.
Cameroon completed.
Canada completed.
Chad completed.
Chile completed.
China completed.
Colombia completed.
Costa Rica completed.
Croatia completed.
Cyprus completed.
Denmark completed.
Dominican Republic completed.
Ecuador completed.
Egypt completed.
El Salvador completed.
Finland completed.
France completed.
Georgia completed.
Germany completed.
Ghana completed.
Greece completed.
Guatemala completed.
Honduras completed.
Hungary completed.
India completed.
Indonesia completed.
Ireland completed.
Israel completed.
Italy completed.
Japan completed.
Jordan completed.
Kazakhstan completed.
Kenya completed.
Kosovo completed.
Kyrgyzstan completed.
Lebanon completed.
Lithuania completed.
Luxembourg completed.
Mali completed.
Malta completed.
Mauritania completed.
Mexico completed.
Moldova completed.
Mongolia completed.
Montenegro completed.
Nepal completed.
Netherlands completed.
New Zealand completed.
Nicaragua completed.
Niger completed.
COUNTRY FAILED - North Macedonia
Pakistan completed.
COUNTRY FAILED - Palestinian Territories
Panama completed.
Peru completed.
Philippines completed.
Poland completed.
Portugal completed.
Romania completed.
Russia completed.
Saudi Arabia completed.
Senegal completed.
Serbia completed.
Slovakia completed.
Slovenia completed.
South Africa completed.
South Korea completed.
Spain completed.
Sweden completed.
COUNTRY FAILED - Taiwan Province of China
Tajikistan completed.
Tanzania completed.
Thailand completed.
Tunisia completed.
Turkey completed.
Uganda completed.
Ukraine completed.
United Arab Emirates completed.
United Kingdom completed.
United States completed.
Uruguay completed.
Uzbekistan completed.
Venezuela completed.
Vietnam completed.
Yemen completed.
Zimbabwe completed.